# check=skip=JSONArgsRecommended
FROM php:8.2-fpm

# Instala dependencias necesarias + dockerize
RUN apt-get update && apt-get install -y libzip-dev zip unzip git curl wget \
    && docker-php-ext-install pdo_mysql zip \
    && wget https://github.com/jwilder/dockerize/releases/download/v0.7.0/dockerize-linux-amd64-v0.7.0.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.7.0.tar.gz

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .

RUN composer install --no-dev --optimize-autoloader
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

EXPOSE 8001

# CMD usando dockerize para esperar a MySQL
CMD dockerize -wait tcp://mysql:3306 -timeout 60s php artisan serve --host=0.0.0.0 --port=8001
