FROM php:8.2-fpm

# Instala dependencias necesarias
RUN apt-get update && apt-get install -y libzip-dev zip unzip git curl wget \
    && docker-php-ext-install pdo_mysql zip

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .

RUN composer install --no-dev --optimize-autoloader
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 8001

# Ejecuta php-fpm
CMD ["sh", "-c", "dockerize -wait tcp://mysql:3306 -timeout 60s php artisan serve --host=0.0.0.0 --port=8001"]
